"""create url mappings table

Revision ID: ef3dfa01ea94
Revises: 
Create Date: 2026-07-09 00:15:08.117591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3dfa01ea94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_url_mappings_id'), 'url_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_url_mappings_short_code'), 'url_mappings', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_mappings_short_code'), table_name='url_mappings')
    op.drop_index(op.f('ix_url_mappings_id'), table_name='url_mappings')
    op.drop_table('url_mappings')
    # ### end Alembic commands ###
